# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67f3364854bb60c686383ff55e82fbb55c429d02e22ac6e15438086d834980105978b4619284ec490524da48708e5668a6820556f9eb0591203f8d494730570e

test:
  secret_key_base: eb9be3e2b1a4242615741e088d8b850eec741448bf759a000c20f81a8231be084b378deda5bab3a314ea114584f6abe5776592dd3e2577ec359f830aa86a830e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
